---
# Installation tasks
- name: Download Checksum file
  get_url:
    url: "{{ _zimbra_urls[zbox_zimbra.installer_type][zbox_zimbra.installer_version][zbox_zimbra.installer_os].sha256 }}"
    dest: "{{ zbox_zimbra.check256sum_file }}"
    timeout: "{{ zbox_zimbra.fetch_timeout_seconds }}"

- name: Register sha256 digest
  command: cut -d" " -f1 "{{ zbox_zimbra.check256sum_file }}"
  register: check256sum

- name: Download Zimbra installation file
  get_url: 
    url: "{{ _zimbra_urls[zbox_zimbra.installer_type][zbox_zimbra.installer_version][zbox_zimbra.installer_os].tgz }}"
    dest: "{{ zbox_zimbra.installation_file }}"
    checksum: "sha256:{{ check256sum.stdout }}"
    timeout: "{{ zbox_zimbra.fetch_timeout_seconds }}"

- name: Untar Zimbra installation file
  unarchive:
    src: "{{ zbox_zimbra.installation_file }}"
    dest: /tmp/
    copy: no

- name: Copy Zimbra installation config
  template:
    src: zimbra_install.conf.j2
    dest: /tmp/zimbra_install.conf

- name: Install Zimbra Software
  shell: yes 'Y' | {{ zbox_zimbra.temp_install_dir }}/install.sh -s --platform-override -x /tmp/zimbra_install.conf
  args:
    chdir: "{{ zbox_zimbra.temp_install_dir }}"

- name: Provision Zimbra config
  shell: /opt/zimbra/libexec/zmsetup.pl -c /tmp/zimbra_install.conf
  args:
    chdir: "{{ zbox_zimbra.temp_install_dir }}"
  